Store domain information
wiretrustee/wiretrustee pull request #217
Opened 2022-02-02 17:24 UTC by mlsmaycon

2022-02-02 17:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wiretrustee/wiretrustee?pullRequest=217) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wiretrustee/wiretrustee?pullRequest=217) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wiretrustee/wiretrustee?pullRequest=217) it.</sub>

2022-02-09 13:31 UTC, mlsmaycon commented
@braginini  As we discussed, will be better to make room for multitenancy on the storage schema first

2022-02-11 11:05 UTC, braginini approved these changes

2022-02-11 11:07 UTC, braginini requested changes
need account_test that checks domain

2022-02-11 16:17 UTC, braginini approved these changes

2022-02-11 16:18 UTC, merged